[options]
# ============================================
# TENNIS CLUB PROJECT - ODOO 18
# ============================================

# Database
db_host = localhost
db_port = 5432
db_user = admin
db_password = admin

# Addons path - Odoo 18
addons_path = /home/vboxuser/Git/odoo/addons,/home/vboxuser/Git/odoo/odoo/addons,/home/vboxuser/tennis_project/tennis_addons

# HTTP
http_port = 8018
http_interface = 0.0.0.0

# Logs
logfile = /home/vboxuser/tennis_project/logs/odoo.log
log_level = info
log_handler = :INFO

# Data directory
data_dir = /home/vboxuser/tennis_project/data

# Dev mode (раскомментировать при разработке)
# dev_mode = reload,qweb,werkzeug,xml

# Workers
workers = 0

# Limits
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
