# -*- coding: utf-8 -*-
from odoo import api, fields, models
from odoo.exceptions import ValidationError


class HrEmployee(models.Model):
    """Extend Employee for Tennis Trainers."""

    _inherit = "hr.employee"

    is_trainer = fields.Boolean(
        string="Is Trainer",
        default=False,
        help="Check if this employee is a tennis trainer",
    )

    center_id = fields.Many2one(
        comodel_name="tennis.center",
        string="Tennis Center",
        help="Tennis center where the trainer works",
        ondelete="restrict",
    )

    trainer_rate_ids = fields.One2many(
        comodel_name="tennis.trainer.rate",
        inverse_name="trainer_id",
        string="Hourly Rates",
        help="Trainer's hourly rates by training type",
    )

    training_session_count = fields.Integer(
        string="Training Sessions",
        compute="_compute_training_session_count",
        help="Number of training sessions for this trainer",
    )

    # Добавим computed field для общей прибыли тренера
    total_revenue = fields.Monetary(
        string="Total Revenue",
        compute="_compute_total_revenue",
        currency_field="currency_id",
        help="Total revenue generated by this trainer",
    )

    currency_id = fields.Many2one(
        "res.currency",
        string="Currency",
        default=lambda self: self.env.company.currency_id,
    )

    @api.depends("is_trainer")
    def _compute_training_session_count(self):
        """Compute number of training sessions."""
        for trainer in self:
            if trainer.is_trainer:
                trainer.training_session_count = self.env[
                    "tennis.training.session"
                ].search_count([("trainer_id", "=", trainer.id)])
            else:
                trainer.training_session_count = 0

    @api.depends("is_trainer")
    def _compute_total_revenue(self):
        """Compute total revenue for trainer."""
        for trainer in self:
            if trainer.is_trainer:
                sessions = self.env["tennis.training.session"].search(
                    [
                        ("trainer_id", "=", trainer.id),
                        ("status", "=", "completed"),
                    ]
                )
                trainer.total_revenue = sum(sessions.mapped("revenue"))
            else:
                trainer.total_revenue = 0.0

    @api.constrains("is_trainer", "center_id")
    def _check_trainer_center(self):
        """Validate that trainer must be assigned to exactly one center."""
        for employee in self:
            if employee.is_trainer and not employee.center_id:
                raise ValidationError(
                    f"Trainer {employee.name} must be assigned to a Tennis Center."
                )

    @api.constrains("center_id")
    def _check_unique_center(self):
        """Ensure trainer can only be in one center at a time."""
        for employee in self:
            if employee.is_trainer and employee.center_id:
                # Check if there are other records with different centers
                # (this constraint is automatically enforced by the single Many2one field)
                pass


class HrEmployeePublic(models.Model):
    """Extend Employee Public for Tennis Trainers."""
    
    _inherit = "hr.employee.public"
    
    is_trainer = fields.Boolean(
        string="Is Trainer",
        default=False,
        help="Check if this employee is a tennis trainer",
    )
    
    center_id = fields.Many2one(
        comodel_name="tennis.center",
        string="Tennis Center",
        help="Tennis center where the trainer works",
    )
